### ISSUE TITLE
Clarify "port utilization" in 3.7

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#105]
From @evyncke 
In " it was observed that port utilization increased" port is ambiguous: is it IXP physical interface ? UDP/TCP ports ? or something else ?

In the same paragraph, an explanation to the explanation would be welcome.

**Comment by SpencerDawkins** [comment]
Most likely "link utilization", but will check the IAB report (as we're checking the reference link).

**Comment by GrumpyOldTroll** [comment]
"Port utilization" was the terminology used in RFC 9075: https://www.rfc-editor.org/rfc/rfc9075.html#section-3.1.4.  However, I believe they meant "link utilization", the physical links at the IXPs.  I am in favor of changing it to "link utilization", I think that's clearer, but also maybe the better answer is either "port utilization (the physical link)" so that they can search the term in 9075.  Maybe better is to say "link utilization" and add the section reference.

**Comment by SpencerDawkins** [comment]
@GrumpyOldTroll - the reference in RFC 9075 is to https://www.iab.org/wp-content/IAB-uploads/2020/10/covid19-feldmann.pdf, and a quick scan of that position paper for the string " port" makes me fairly confident that they mean "link utilization", as you proposed. 

If we want to be absolutely clear on this point, I note that three of the four workshop report operators are still on the IAB, and we could just ask one or more humans, if we had any doubts ... :sunglasses:

**Comment by acbegen** [comment]
I vote for "link utilization".
