### ISSUE TITLE
Articulate the sources of constraints on bandwidth at different points of the network

### ISSUE THREAD

**Issue by GrumpyOldTroll** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#12]
Pulling the TBD out of the draft text and capturing it here instead.

Suggestion from mic at IETF 106 (Mark Nottingham) in response to call for help on capturing the mismatch between supply and demand of bandwidth with regard to video:
Dive into the different constraints coming from different parts of the network or distribution channels. (regarding questions about how to describe the disconnect between demand vs. capacity, while keeping good archival value.)  "These are big numbers, but the internet has grown over time, and CDN capacities have grown over time.  Is it last mile? Probably not--Is it middle mile?  Maybe that's more interesting.  It it CPU? Is it network cards?  Is it the economics of your peering relationships? Unpicking those bits might help a bit.
https://www.youtube.com/watch?v=4_k340xT2jM&t=13m

**Comment by acbegen** [comment]
For many, poor Wifi is the culprit. For many others, the ISP aggregation links are the culprit during the prime times (since most such links are oversubscribed/oversold). For some, the CDN issues create problems and for rare cases, the origin drowns and everybody gets upset. For certain environments like student dorms, campus networks, libraries, airport cafes, it is just lack of bandwidth for the power users.
