### ISSUE TITLE
Is this document about video streaming, or about media streaming?

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#189]
@GrumpyOldTroll and @acbegen, please let me know what you think. 

I think this document is primarily about video streaming - guidance about the [other top-level media types listed at IANA](https://www.iana.org/assignments/media-types/media-types.xhtml) isn't present in this document. 

We're using both terms in the document, sometimes in the same section. If there are meaningful differences, I can't find them in the document. 

Should we (roughly) s/media/video/g?

**Comment by SpencerDawkins** [comment]
After an editor huddle, we actually ARE talking about more media types than just video, but the major operational considerations we have experience with are mostly pointed toward video.

What we might do, that's not a global replacement, is assume that the document IS about media in general, and make sure that when we do mention video, that's intentional. But we should talk about this before we pull the trigger.

**Comment by acbegen** [comment]
I am biased toward keeping "media" while acknowledging that most of the discussion relates to video. We should use "media" everywhere except where we specifically talk about "video" (for example, if we are talking about resolution, frame rate but not bitrate). Video plays a bigger role in this because of its higher requirements than say audio or timed text.
