### ISSUE TITLE
Adaptive monitoring/feedback loops considerations

### ISSUE THREAD

**Issue by gitnnelg** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#41]
the current draft mentions that TCP has a feedback control mechanism while UDP doesn't etc.  It also mentions ABR but with out much detail on what exactly is going on with ABR.

It may be helpful to the reader to have a section that goes a little bit into the mechanism that are being used at the application level.  while application behavior is often outside of the interest by IETF documents, in this case the application's are making choices and collecting data that are directly connected to network performance, and in turn make changes to the applications use of the network and consequently the video transports impact to the network.     

There are a couple mechanisms  by video applications which could be viewed as essentially seen as application layer network management.    1. ABR - which is lightly mentioned in the current draft,  2. Adaptive encoding, 3. player and edge data collection, coupled with a feedback mechanism to the video server and even the player that cause adaptive change decisions on the data being sent such as systems like Conviva.

Not suggesting a huge section, but something should be included about how application layer monitoring and adaptive decision making by players/servers is a form of network flow/use flow control especially when UDP/QUIC transport is used, but certainly it's impactful for TCP flows.

**Comment by SpencerDawkins** [comment]
Glenn, I think I can also cover this in #35 (which is still moving rapidly, so don't peek at it for a couple of days).

And I really like these observations. I know this topic matters, and I'll do my best to reflect your issue.

**Comment by SpencerDawkins** [comment]
@gitnnelg, after looking at this a bit more, I think most of the work is in what is now called the ABR section, which I haven't touched in #35. I'm going to unlink that PR, and start working on a new one. Please stay tuned.

**Comment by SpencerDawkins** [comment]
Just to follow up here - I think the ABR section is a good start for @gitnnelg's suggested three-part section, which I'm now seeing as four sections - the fourth, describing the challenges that application-level mechanisms have to anticipate in adapting media streams.  I'm planning to use the existing subsections on Idle Time Between Segments, Head-of-Line Blocking, and Unreliable Transports in that fourth section. 

So, as @gitnnelg said - not a huge section (because where would we stop?), but some additional words that provide context for adaptive streaming.
