### ISSUE TITLE
Idle time between segments

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#54]
From Will,

3.2.1 Idle time between Segments

The section talks about consequences of mobile flow-bandwidth and TCP slow start , yet neither of these are relevant to the referenced NOSSDAV12 paper, which talks about a small cohort of adaptive players competing for bandwidth. The paper is a good one (I know one of the authors), but the RFC section text needs to do a better job of summarizing the problems highlighted by that paper.

**Comment by acbegen** [comment]
There are two issues here: First, the on-off behavior of the HTTP streaming traffic.  NOSSDAV12 paper is a good reference describing that behavior and its consequences. This stuff is not explained much in the draft at the moment. I will look into this. Second, the TCP's slow-start restart (SSR) "feature". For that NOSSDAV12 was the wrong reference, it should have been MMSys11, which I fixed for the PR. This second issue may (or may not need further discussion). 

Can we get some feedback from CDN guys as to whether they disable SSR in production for example? @LPardue @GrumpyOldTroll ?

**Comment by GrumpyOldTroll** [comment]
In practice we do a number of things, including some different handling of SSR.  It can be a little complicated because it can depend on what has happened in the flow, so "disabled" might not be exactly the way to think about it, and I think different settings in the config for your assets can perhaps result in different behavior.  I expect also different CDNs have different answers.
This text was intended to raise this as an effect to be aware of if you're operating a server, and a point to check when you're troubleshooting why something is not behaving as expected.  I guess there might be something useful to say about CDNs and other providers that already have techniques in place to mitigate this, is that what you're asking about here?

**Comment by LPardue** [comment]
Not commenting on a specific CDN but, as a general observation, many people tuning HTTP performance will start with something like https://hpbn.co/building-blocks-of-tcp/, which includes some advice for best current practice including disabling SSR

**Comment by SpencerDawkins** [comment]
Fixed in #59.
