### ISSUE TITLE
Update growth numbers in Section 2

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#99]
From @evyncke 
" expected to grow to 82% by 2022" but we are in 2022... better provide numbers for 2021 if they are available (and now I read that the source of the info is my own employer :-O )

**Comment by GrumpyOldTroll** [comment]
I think Cisco publishes a new one of these every year and it keeps having the same cagr, so I'll check the latest ref and update it if it's not too broken.

**Comment by GrumpyOldTroll** [comment]
OK, there's a few problems:

- the reference's link no longer gets you to the referenced pdf.  Found another copy here, but I'm not sure this reference is archived well:
  https://twiki.cern.ch/twiki/pub/HEPIX/TechwatchNetwork/HtwNetworkDocuments/white-paper-c11-741490.pdf
- There's a new report from Cisco from 1 year later, but it doesn't include the same number:
  https://www.cisco.com/c/en/us/solutions/collateral/executive-perspectives/annual-internet-report/white-paper-c11-741490.html
- Web searching doesn't seem to find anyone publishing an estimate of the share of video traffic (nor its trend forecast) for later years.  I imagine this got trickier to collect with the ubiquitous deployment of encryption?

So I'm thinking instead of updating the reference and getting newer numbers, we maybe update the wording to make it more clear we're just using an old estimate since that's what we have.  Suggested text:

OLD:
As the internet has grown, an increasingly large share of the traffic delivered to end users has become video. Estimates put the total share of internet video traffic at 75% in 2019, expected to grow to 82% by 2022. This estimate projects the gross volume of video traffic will more than double during this time, based on a compound annual growth rate continuing at 34% (from Appendix D of [CVNI]).

NEW:
As the internet has grown, an increasingly large share of the traffic delivered to end users has become video. The most recent available estimates found that 75% of the total traffic to end users was video in 2019 and the share of video was projected to grow to 82% by 2022. The same analysis also projected the gross volume of video traffic to more than double during that time (from Appendix D of [CVNI]).

**Comment by SpencerDawkins** [comment]
@GrumpyOldTroll - I'm thinking (so you've been warned) that the point we need to make here may not be that the **share** of video traffic is growing, but that even with the 2017 number for 2017, it was already 75 percent, and increasing.

So if you see total traffic go up by 15 percent, it's reasonable to assume that video traffic also went up by something very close to 15 percent. 

I agree with your assessment that observation points that can't decrypt encrypted traffic will find it increasingly difficult to identify video traffic, so any opinions about the percentage of total traffic being video will be more suspect every year, and chasing newer numbers isn't likely to be helpful.

Thoughts?

**Comment by acbegen** [comment]
Yeah, we should not really chase the latest number, which is a moving target. What @GrumpyOldTroll proposed works for me.
